name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - '**.gradle'
      - '**.properties'

env:
  MOD_VERSION: 1.0.0

jobs:
  build_1_20_1:
    name: Build 1.20.1
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build & Maven Publish
        run: ./gradlew build --stacktrace
      - name: Upload release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: 'sons_of_macabre_${{env.MOD_VERSION}}-all.jar'
          tag: release
          allowUpdates: true